### ISSUE TITLE
[gl-react-expo@3.6.0] TypeError: loader.getSize is not a function

### ISSUE THREAD

**Issue by serhiipalash** [gre/gl-react#156]
I get error `TypeError: loader.getSize is not a function` with latest `gl-react-expo@3.6.0`, but with `gl-react-expo@3.13.0` all works fine.

#### library version

<img width="516" alt="screen shot 2017-09-08 at 15 59 43" src="https://user-images.githubusercontent.com/14208343/30212828-3d1910a8-94af-11e7-977f-23d7d75640a5.png">

### *bug report*

<img width="1280" alt="screen shot 2017-09-08 at 15 50 26" src="https://user-images.githubusercontent.com/14208343/30212856-57a0c3d0-94af-11e7-834f-b44023d3f2ca.png">

#### Expected behavior

Works with gl-react-expo@3.13.0

<img width="1280" alt="screen shot 2017-09-08 at 15 51 52" src="https://user-images.githubusercontent.com/14208343/30212880-6c270b98-94af-11e7-81d2-036e597c58dc.png">

#### Steps to reproduce the behavior

Clone this repo and open in Expo XDE

https://github.com/serhiipalash/opengl-test

**Comment by gre** [comment]
> I get error TypeError: loader.getSize is not a function with latest gl-react-expo@3.6.0

as this v3 is still in alpha, assume breaking changes across different version, for gl-react@3.13.0 please use gl-react-expo@3.13.0

the issue is more because of this:

```
npm dist-tag ls gl-react-expo
latest: 3.6.0
next: 3.13.0
```

I should never have published such a "latest" as the current v3 should be considered on "next" and gl-react-expo@latest shouldn't have existed. sorry for that

**Comment by serhiipalash** [comment]
NP. Thanks! You have a great library!
